-- Deterministic dev/test catalog seed (sok-replica.3.6)
-- Sources: fixtures/catalog_seed.json (extracted from mirrored templates/docs/raw)
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE video_channels;
TRUNCATE TABLE video_pornstars;
TRUNCATE TABLE video_categories;
TRUNCATE TABLE videos;
TRUNCATE TABLE categories;
TRUNCATE TABLE pornstars;
TRUNCATE TABLE channels;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('milf', "MILF", "https://c.foxporn.tv/fox-images/categories/milf.jpg", 12, 0);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('big-tits', "Big Tits", "https://c.foxporn.tv/fox-images/categories/big-tits.jpg", 19136, 1);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('bdsm', "BDSM", "https://c.foxporn.tv/fox-images/categories/bdsm.jpg", 345, 2);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('japanese', "Japanese", "https://c.foxporn.tv/fox-images/categories/japanese.jpg", 451, 3);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('doggy-style', "Doggy Style", "https://c.foxporn.tv/fox-images/categories/doggy-style.jpg", 15341, 4);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('indian', "Indian", "https://c.foxporn.tv/fox-images/categories/indian.jpg", 318, 5);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('dildo', "Dildo", "https://c.foxporn.tv/fox-images/categories/dildo.jpg", 1475, 6);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('asian', "Asian", "https://c.foxporn.tv/fox-images/categories/asian.jpg", 2105, 7);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('thai', "Thai", "https://c.foxporn.tv/fox-images/categories/thai.jpg", 92, 8);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('chinese', "Chinese", "https://c.foxporn.tv/fox-images/categories/chinese.jpg", 133, 9);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('midget', "Midget", "https://c.foxporn.tv/fox-images/categories/midget.jpg", 30, 10);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('mature', "Mature", "https://c.foxporn.tv/fox-images/categories/mature.jpg", 2603, 11);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('big-ass', "Big Ass", "https://c.foxporn.tv/fox-images/categories/big-ass.jpg", 14794, 12);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('glory-hole', "Glory Hole", "https://c.foxporn.tv/fox-images/categories/glory-hole.jpg", 112, 13);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('orgy', "Orgy", "https://c.foxporn.tv/fox-images/categories/orgy.jpg", 889, 14);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('big-nipples', "Big Nipples", "https://c.foxporn.tv/fox-images/categories/big-nipples.jpg", 132, 15);
INSERT INTO categories (slug, display_name, thumb_url, video_count, sort_order) VALUES ('hardcore', "Hardcore", "https://c.foxporn.tv/fox-images/categories/hardcore.jpg", 26424, 16);

INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (18, 'your-priya', "YOUR PRIYA", "fox-images/pornstars/your-priya.jpg", 31, 31000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (19, 'sapphire-lapiedra', "Sapphire Lapiedra", "fox-images/pornstars/sapphire-lapiedra.jpg", 7, 7000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (20, 'yourxdarling', "yourxdarling", "fox-images/pornstars/yourxdarling.jpg", 11, 11000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (21, 'garmia', "Garmia", "fox-images/pornstars/garmia.jpg", 2, 2000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (22, 'savannah-watson', "Savannah Watson", "fox-images/pornstars/savannah-watson.jpg", 50, 50000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (23, 'chloe-cherry', "Chloe Cherry", "fox-images/pornstars/chloe-cherry.jpg", 121, 121000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (24, 'athena-faris', "Athena Faris", "fox-images/pornstars/athena-faris.jpg", 43, 43000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (25, 'thestartofus', "THESTARTOFUS", "fox-images/pornstars/thestartofus.jpg", 47, 47000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (26, 'pkgulnaz', "Pkgulnaz", "data:image/gif;base64,R0lGODlhAQABAJAAAAAAAAAAACH5BAEUAAAALAAAAAABAAEAAAICRAEAOw==", 4, 4000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (27, 'yoursoniya', "Yoursoniya", "data:image/gif;base64,R0lGODlhAQABAJAAAAAAAAAAACH5BAEUAAAALAAAAAABAAEAAAICRAEAOw==", 7, 7000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (28, 'kelly-aleman', "Kelly Aleman", "data:image/gif;base64,R0lGODlhAQABAJAAAAAAAAAAACH5BAEUAAAALAAAAAABAAEAAAICRAEAOw==", 131, 131000);
INSERT INTO pornstars (id, slug, display_name, thumb_path, video_count, week_views) VALUES (29, 'riley-reid', "Riley Reid", "data:image/gif;base64,R0lGODlhAQABAJAAAAAAAAAAACH5BAEUAAAALAAAAAABAAEAAAICRAEAOw==", 270, 270000);

INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (1, 'my-pervy-family', "My Pervy Family", "fox-images/channels/my-pervy-family.jpg", 61, 30500);
INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (2, 'i-fucked-her-finally', "I Fucked Her Finally", "fox-images/channels/i-fucked-her-finally.jpg", 127, 63500);
INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (3, 'teen-mega-world', "Teen Mega World", "fox-images/channels/teen-mega-world.jpg", 343, 171500);
INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (4, 'pornstar-platinum', "Pornstar Platinum", "fox-images/channels/pornstar-platinum.jpg", 108, 54000);
INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (5, 'vixen', "Vixen", "fox-images/channels/vixen.jpg", 195, 97500);
INSERT INTO channels (id, slug, title, thumb_path, video_count, week_views) VALUES (6, 'wow-girls', "Wow Girls", "fox-images/channels/wow-girls.jpg", 260, 130000);

INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (1, 'athena-faris-sneaks-out-of-alexs-gym-bag-joins-him-his-wifey-chloe-cherry-in-bed', "Athena Faris Sneaks out of Alex's Gym Bag & Joins him & his wifey Chloe Cherry in Bed", 703, "https://c.foxporn.tv/fox-images/videos/athena-faris-sneaks-out-of-alexs-gym-bag-joins-him-his-wifey-chloe-cherry-in-bed.jpg", "https://c.foxporn.tv/fox-images/videos/m-athena-faris-sneaks-out-of-alexs-gym-bag-joins-him-his-wifey-chloe-cherry-in-bed.mp4", 22063, 70, 30, 0, '2026-04-18', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (2, 'victoria-rae-cumshot-and-orgasm-compilation-onlyfans', "Victoria Rae Cumshot and Orgasm Compilation - OnlyFans", 503, "https://c.foxporn.tv/fox-images/videos/victoria-rae-cumshot-and-orgasm-compilation-onlyfans.jpg", "https://c.foxporn.tv/fox-images/videos/m-victoria-rae-cumshot-and-orgasm-compilation-onlyfans.mp4", 36301, 82, 18, 3, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (3, 'ava-devine-assfucked-and-sucks-cock', "Ava Devine Assfucked and Sucks Cock", 601, "https://c.foxporn.tv/fox-images/videos/ava-devine-assfucked-and-sucks-cock.jpg", "https://c.foxporn.tv/fox-images/videos/m-ava-devine-assfucked-and-sucks-cock.mp4", 21861, 84, 16, 4, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (4, 'riley-steele-erik-everhard-deceptions', "Riley Steele & Erik Everhard - Deceptions", 480, "https://c.foxporn.tv/fox-images/videos/riley-steele-erik-everhard-deceptions.jpg", "https://c.foxporn.tv/fox-images/videos/m-riley-steele-erik-everhard-deceptions.mp4", 13653, 73, 27, 1, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (5, 'moms-girl-sarah-vandella-brings-athena-faris-and-lily-larimars-overnight-to-the-next-level', "Mom'S GIRL - Sarah Vandella Brings Athena Faris and Lily Larimar's Overnight to the next Level", 720, "https://c.foxporn.tv/fox-images/videos/moms-girl-sarah-vandella-brings-athena-faris-and-lily-larimars-overnight-to-the-next-level.jpg", "https://c.foxporn.tv/fox-images/videos/m-moms-girl-sarah-vandella-brings-athena-faris-and-lily-larimars-overnight-to-the-next-level.mp4", 12936, 67, 33, 1, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (6, 'newly-cheerleader-asian-lulu-chu-learns-the-basics-with-her-captain-pussy-eating-and-facesitting', "Newly Cheerleader Asian LuLu Chu Learns the Basics with her Captain - PUSSY EATING and FACESITTING", 759, "https://c.foxporn.tv/fox-images/videos/newly-cheerleader-asian-lulu-chu-learns-the-basics-with-her-captain-pussy-eating-and-facesitting.jpg", "https://c.foxporn.tv/fox-images/videos/m-newly-cheerleader-asian-lulu-chu-learns-the-basics-with-her-captain-pussy-eating-and-facesitting.mp4", 10158, 81, 19, 1, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (7, 'foot-fetish-with-maddy-oreilly-jasmine-wolff-and-more', "Foot Fetish with Maddy O'Reilly, Jasmine Wolff and more", 474, "https://c.foxporn.tv/fox-images/videos/foot-fetish-with-maddy-oreilly-jasmine-wolff-and-more.jpg", "https://c.foxporn.tv/fox-images/videos/m-foot-fetish-with-maddy-oreilly-jasmine-wolff-and-more.mp4", 6428, 88, 12, 0, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (8, 'big-butted-blonde-christie-stevens-cheating-on-her-husband-in-dp-threesome-with-her-fuck-buddies', "Big-butted Blonde Christie Stevens Cheating on her husband in DP Threesome with her Fuck-buddies", 781, "https://c.foxporn.tv/fox-images/videos/big-butted-blonde-christie-stevens-cheating-on-her-husband-in-dp-threesome-with-her-fuck-buddies.jpg", "https://c.foxporn.tv/fox-images/videos/m-big-butted-blonde-christie-stevens-cheating-on-her-husband-in-dp-threesome-with-her-fuck-buddies.mp4", 14789, 71, 29, 1, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (9, 'real-estate-agents-jade-kush-ember-snow-seduce-client-into-hot-sex-letsdoeit', "Real Estate Agents Jade Kush & Ember Snow Seduce Client into hot sex - LETSDOEIT", 1050, "https://c.foxporn.tv/fox-images/videos/real-estate-agents-jade-kush-ember-snow-seduce-client-into-hot-sex-letsdoeit.jpg", "https://c.foxporn.tv/fox-images/videos/m-real-estate-agents-jade-kush-ember-snow-seduce-client-into-hot-sex-letsdoeit.mp4", 6814, 71, 29, 0, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (10, 'fun-sized-blondie-alicia-williams-tight-butthole-banged', "Fun Sized Blondie Alicia Williams' Tight Butthole banged", 744, "https://c.foxporn.tv/fox-images/videos/fun-sized-blondie-alicia-williams-tight-butthole-banged.jpg", "https://c.foxporn.tv/fox-images/videos/m-fun-sized-blondie-alicia-williams-tight-butthole-banged.mp4", 10817, 80, 20, 1, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (11, 'redhead-bitch-dirty-sloppy-blow-job-cum-on-face-big-pawg-ginger-sucks', "Redhead bitch Dirty Sloppy blow job - Cum on Face | Big PAWG Ginger Sucks", 721, "https://c.foxporn.tv/fox-images/videos/redhead-bitch-dirty-sloppy-blow-job-cum-on-face-big-pawg-ginger-sucks.jpg", "https://c.foxporn.tv/fox-images/videos/m-redhead-bitch-dirty-sloppy-blow-job-cum-on-face-big-pawg-ginger-sucks.mp4", 4211, 88, 12, 0, '2026-03-09', 0, 1, 'published');
INSERT INTO videos (id, slug, title, duration_seconds, thumb_url, preview_mp4, views, likes_up, likes_down, comment_count, published_at, is_hd, wide_thumb, status) VALUES (12, 'real-teenagers-savannah-sixx-fucked-during-porn-casting', "Real teenagers - Savannah Sixx Fucked during Porn Casting", 720, "https://c.foxporn.tv/fox-images/videos/real-teenagers-savannah-sixx-fucked-during-porn-casting.jpg", "https://c.foxporn.tv/fox-images/videos/m-real-teenagers-savannah-sixx-fucked-during-porn-casting.mp4", 12889, 70, 30, 0, '2026-03-09', 0, 1, 'published');

INSERT INTO video_categories (video_id, category_id) VALUES (1, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (1, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (1, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (2, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (2, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (2, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (3, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (3, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (3, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (4, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (4, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (4, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (5, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (5, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (5, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (6, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (6, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (6, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (7, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (7, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (7, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (8, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (8, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (8, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (9, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (9, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (9, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (10, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (10, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (10, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (11, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (11, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (11, 3);
INSERT INTO video_categories (video_id, category_id) VALUES (12, 1);
INSERT INTO video_categories (video_id, category_id) VALUES (12, 2);
INSERT INTO video_categories (video_id, category_id) VALUES (12, 3);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (1, 18);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (2, 19);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (3, 20);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (4, 21);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (5, 22);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (6, 23);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (7, 24);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (8, 25);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (9, 26);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (10, 27);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (11, 28);
INSERT INTO video_pornstars (video_id, pornstar_id) VALUES (12, 29);
INSERT INTO video_channels (video_id, channel_id) VALUES (1, 1);
INSERT INTO video_channels (video_id, channel_id) VALUES (2, 2);
INSERT INTO video_channels (video_id, channel_id) VALUES (3, 3);
INSERT INTO video_channels (video_id, channel_id) VALUES (4, 4);
INSERT INTO video_channels (video_id, channel_id) VALUES (5, 5);
INSERT INTO video_channels (video_id, channel_id) VALUES (6, 6);
INSERT INTO video_channels (video_id, channel_id) VALUES (7, 1);
INSERT INTO video_channels (video_id, channel_id) VALUES (8, 2);
INSERT INTO video_channels (video_id, channel_id) VALUES (9, 3);
INSERT INTO video_channels (video_id, channel_id) VALUES (10, 4);
INSERT INTO video_channels (video_id, channel_id) VALUES (11, 5);
INSERT INTO video_channels (video_id, channel_id) VALUES (12, 6);
